services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: backend_citas
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Forencia14.
      - MSSQL_PID=Developer
    ports:
      - "1533:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: Web_back/Dockerfile
    container_name: api_citas
    depends_on:
      - sql
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sql,1433;Database=hospital;User Id=sa;Password=Forencia14.;TrustServerCertificate=True;
    ports:
      - "5000:8080"

volumes:
  mssql_data:
